#!/bin/bash

echo "🔧 Ritual7 Provisioning Profile Fix"
echo "====================================="
echo ""
echo "These errors need to be fixed in the Apple Developer Portal and Xcode:"
echo ""
echo "1. ✅ PLA (Program License Agreement)"
echo "   → Go to: https://developer.apple.com/account"
echo "   → Sign in with your Apple Developer account"
echo "   → Agree to the latest Program License Agreement if prompted"
echo "   → Wait 2-3 minutes for the agreement to process"
echo ""
echo "2. ✅ Enable Capabilities in App ID"
echo "   → Go to: https://developer.apple.com/account/resources/identifiers/list"
echo "   → Find your App ID (e.g., com.williamalston.workout or similar)"
echo "   → Click 'Edit'"
echo "   → Enable these capabilities:"
echo "     • HealthKit"
echo "     • App Groups"
echo "   → For App Groups, add: group.com.williamalston.workout"
echo "   → Click 'Save'"
echo ""
echo "3. ✅ Refresh Provisioning Profiles in Xcode"
echo "   → Open Xcode"
echo "   → Go to: Xcode → Settings (⌘,) → Accounts"
echo "   → Select your Apple ID"
echo "   → Select your team (AYZ9SP42W8)"
echo "   → Click 'Download Manual Profiles'"
echo "   → Wait for profiles to download"
echo ""
echo "4. ✅ Clean Build"
echo "   → In Xcode: Product → Clean Build Folder (⇧⌘K)"
echo "   → Close Xcode"
echo "   → Reopen Xcode"
echo "   → Product → Build (⌘B)"
echo ""
echo "Current Configuration:"
echo "  • Team ID: AYZ9SP42W8"
echo "  • App Group: group.com.williamalston.workout"
echo "  • HealthKit: Enabled"
echo "  • Entitlements: ✅ Correct"
echo ""
echo "If you're using a free Apple Developer account, note that:"
echo "  • HealthKit requires a paid Apple Developer Program membership"
echo "  • App Groups work with free accounts"
echo ""


